name: PHP Linting
on: push
jobs:
  phplint:
    runs-on: ubuntu-latest
    steps:
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - name: Run phpcodesniffer
        run: ./vendor/squizlabs/php_codesniffer/bin/phpcs . 
